version: "3.8"
services:
  db:
    hostname: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${TOMUDO_DB_USER}
      POSTGRES_PASSWORD: ${TOMUDO_DB_PW}
      POSTGRES_DB: ${TOMUDO_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - tomudo
    command: -p ${TOMUDO_DB_PORT}

  todo:
    build:
      context: ./todo
    hostname: todo
    networks:
      - tomudo
    depends_on:
      - db
    environment:
      PORT: ${TOMUDO_TODO_PORT}
      TOMUDO_DB_USER: ${TOMUDO_DB_USER}
      TOMUDO_DB_PW: ${TOMUDO_DB_PW}
      TOMUDO_DB_NAME: ${TOMUDO_DB_NAME}
      TOMUDO_DB_PROTOCOL: ${TOMUDO_DB_PROTOCOL}
      TOMUDO_DB_HOST: ${TOMUDO_DB_HOST}
      TOMUDO_DB_PORT: ${TOMUDO_DB_PORT}
      TOMUDO_TODO_PORT: ${TOMUDO_TODO_PORT}



  shopping-list:
    build:
      context: ./shopping-list
    hostname: shopping-list
    networks:
      - tomudo
    depends_on:
      - todo
    environment:
      PORT: ${TOMUDO_SHOPPING_LIST_PORT}
      TOMUDO_SHOPPING_LIST_PORT: ${TOMUDO_SHOPPING_LIST_PORT}
      TOMUDO_TODO_HOST: ${TOMUDO_TODO_HOST}
      TOMUDO_TODO_PORT: ${TOMUDO_TODO_PORT}

volumes:
  db:

networks:
  tomudo:
    external: True

